//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFileApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX")]
        public string DefaultState {
            get {
                return ((string)(this["DefaultState"]));
            }
            set {
                this["DefaultState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.uslegalpro.com/v2/")]
        public string ProdApiEndPoint {
            get {
                return ((string)(this["ProdApiEndPoint"]));
            }
            set {
                this["ProdApiEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api-stage.uslegalpro.com/v2/")]
        public string StageApiEndPoint {
            get {
                return ((string)(this["StageApiEndPoint"]));
            }
            set {
                this["StageApiEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staging")]
        public string DefaultEnviornment {
            get {
                return ((string)(this["DefaultEnviornment"]));
            }
            set {
                this["DefaultEnviornment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/uslegalpro/bulk/templates")]
        public string DefaultTemplateLocation {
            get {
                return ((string)(this["DefaultTemplateLocation"]));
            }
            set {
                this["DefaultTemplateLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/uslegalpro/bulk/bulk1.tsv")]
        public string DefaultTsvFile {
            get {
                return ((string)(this["DefaultTsvFile"]));
            }
            set {
                this["DefaultTsvFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLoginStateEnv {
            get {
                return ((string)(this["LastLoginStateEnv"]));
            }
            set {
                this["LastLoginStateEnv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/uslegalpro/bulk/stamped")]
        public string DefaultOutpuLocation {
            get {
                return ((string)(this["DefaultOutpuLocation"]));
            }
            set {
                this["DefaultOutpuLocation"] = value;
            }
        }
    }
}
